sonar.organization=nekomanaja
sonar.projectKey=nekomanaja_Final-Project

sonar.sources=client/src,server
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**,**/*.test.js,**/setupTests.js,client/public/**
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
sonar.sourceEncoding=UTF-8